[package]
name = "mcp3425"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]

[dependencies]
byteorder = "1.2"
embedded-hal = "0.1.0"

[dev-dependencies]
linux-embedded-hal = "0.1.1"

[profile.release]
lto = true
